# Generated by Django 4.0.4 on 2022-08-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_attendance_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedata',
            name='status',
            field=models.IntegerField(),
        ),
    ]
