# Generated by Django 3.2.15 on 2022-08-23 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_attendance_rest_api', '0005_alter_class_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='child_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kindergarten_attendance_rest_api.child'),
            preserve_default=False,
        ),
    ]
