# Generated by Django 3.2.5 on 2022-08-25 08:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_attendance_rest_api', '0008_alter_attendancedata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 17, 21, 25, 695645), max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancedata',
            name='status',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
